URL := "netbox.devops.map.cisco"
PROXY := "localhost:9876"
TOKEN := `op read op://Cisco/netbox-api/credential`
ITE := '100.64.0.0/10'
MAP := '100.88.0.0/13'
CISCO := ''
SCHEMA := "netbox/introspected.json"

introspect:
    @if [ ! -f {{SCHEMA}} ]; then \
        curl -s \
            -H "Authorization: Token {{TOKEN}}" \
            -H "Accept: application/json; indent=4" \
            -H "Content-Type: application/json" \
            -x socks5://{{PROXY}} \
            -X POST \
            "https://{{URL}}/graphql/" \
            -d "$(jq -c -n --arg query "$(cat netbox/introspect.gql)" '{"query":$query}')" \
            | jq '.' > {{SCHEMA}}; \
    fi

curl:
    @curl -s \
        -H "Authorization: Token {{TOKEN}}" \
        -H "Accept: application/json; indent=4" \
        -H "Content-Type: application/json" \
        -x socks5://{{PROXY}} \
        -X POST \
        "https://{{URL}}/graphql/" \
        --data "$(jq -c -n --arg query "$(cat netbox/query.gql)" '{"query":$query}')" \
        | jq '.'

# List the GraphQL Schema Types by name
list: introspect
    @jq '.data.__schema.types[].name' {{SCHEMA}}

# Use one of the Schema Type Names given by 'just list' to explore a types fields
explore target: introspect
    @jq '.data.__schema.types[] | select(.name == "{{target}}") | .fields[].name' {{SCHEMA}}

# -d "$(jq -c -n --arg query "$(cat query.gql)" --argjson variables '{"jobTitle": "janitor"}' '{"query":$query,"variables":$variables}')" \
# --data '{"query": "query {__schema {types {name fields {name description}}}}"}' \
# -d "$(jq -c -n --arg query "$(cat netbox/introspect.gql)" '{"query":$query')" \
# | jq '.' > netbox/introspected.1.json; \
# get-next-cidr
# get-next-cidr
# --data '{"query": "query {prefix_list(=) {cid provider {name}}}"}'
# --data "$(jq -c -n --arg query "$(cat netbox/query.gql)" '{"query":$query}')" \
# --data '{"query": "query {prefix_list {id description prefix}}"}' \
