default := (pyv 3.13)

bundle := "~/combine/map-il5/certificates/ca-chain.cert.pem"

prereqs pyv:
    if [ ! command -v pyenv ]; then
        echo "installing pyenv"
        brew install pyenv
        pyenv install "{{pyv}}"
    fi
    if [ pip -vvv freeze -r requirements.txt | grep -q "not installed" ]; then
        pip3 install -r requirements.txt
        pip3 install virtualenvwrapper
        pip3 install pproxy
    fi
    if [ ! -f ${HOME}/.local/data/certs/combine/map-il5/ca-chain.cert.pem ] ; then
        echo "CA Chain file for 'combine-w4g-il5' not found"
        return 1
    fi

shell pyv:
    pyenv shell "{{pyv}}"
    virtualenv pproxy


ssh target:
    source .zshrc
    pproxy -vv -r socks5://localhost:9001 -l http+socks4+socks5://:9000/ -d
    ssh combine-w4g-il5-bastion -F ./config

enter:
    export pproxy_addr=http://localhost:9000
    export ALL_PROXY=${pproxy_addr}
    export HTTPS_PROXY=${pproxy_addr}
    export HTTP_PROXY=${pproxy_addr}
    export https_proxy=${pproxy_addr}
    export http_proxy=${pproxy_addr}
    export KUBE_PROXY_URL=${pproxy_addr}
    export AWS_CA_BUNDLE="${bundle}"
    export PROMPT_ORIG="$PROMPT"
    export PROMPT="$(proxy_prompt_info)$PROMPT"

exit:
    export PROMPT="$PROMPT_ORIG"
    unset PROMPT_ORIG
    just clean

clean:
    unset pproxy_addr
    unset ALL_PROXY
    unset HTTPS_PROXY
    unset HTTP_PROXY
    unset https_proxy
    unset http_proxy
    unset KUBE_PROXY_URL
    unset AWS_CA_BUNDLE
