claude:
    echo "TODO: Setup repo for claude code integration, using .ai/* contents"

opencode:
    echo "TODO: Setup repo for OpenCode integration, using .ai/* contents"

zed:
    echo "TODO: Setup repo for zed agent integration, using .ai/* contents"

vscode:
    echo "TODO: Setup repo for vscode integration, using .ai/* contents"

windsurf:
    echo "TODO: Setup repo for windsurf agent integration, using .ai/* contents"

cursor:
    echo "TODO: Setup repo for cursor agent integration, using .ai/* contents"

mcp-tools:
    echo "TODO: Setup mcp-tools for repo"
